### ISSUE TITLE
Enable/Disable Privacy Guard does not work (Exception error)

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#10]
Test version: v0.9.3

When Run "Enable Privacy Guard" Exception error occurs.

************* Outer Exception **************
例外タイプ：System.NullReferenceException
例外メッセージ：オブジェクト参照がオブジェクト インスタンスに設定されていません。
例外ソース：Maximizer.Plugins
例外対象サイト： MoveNext
   場所 Maximizer.Plugins.Client.MaximizerToolbarPluginWpfUserControl.b.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

************** System Info **************
日時：	2023/07/21 11:54:51
マシン名：	DESKTOP-S6JNAMR
プロセッサの数：	16
OS バージョン：	Microsoft Windows NT 6.2.9200.0
64 ビット OS:	True
64 ビット プロセス：	True
IPアドレス：	fe80::ced1:a739:5605:13dd%13 (DESKTOP-S6JNAMR)
現行ユーザー：	DESKTOP-S6JNAMR\IPRO_VMS_TEST

Ref.
On management client, "Request Path" for both Enable Privacy Guard and Disable Privacy Guard is "cgi-bin/".
But we do not think this is problem because Request Path changes depends on camera's schedule configuration.

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/7965ca45-4e68-40f7-b5ca-b40738ba1ca8)

@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Solved for v0.9.4

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v0.9.4
Test Result: not OK.

When we select enable or disable from Smart client, camera's schedule configuration has not been updated.

According to Wireshark packet, plug-in does not send commant to Set (/cgi-in/setdata).
Only getdata is sent.
@alexnaicuorbnet

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet  @EricBourque 
We are now testing using v0.9.5 and want to know how to delete plug-in's configuration (data for restore command, Extended action's configuration and so on.
This is because our one test environment does not show "Restore" option and Enable/Disable command did not work. But when we use another PC, "Restore" command is shown and Enable/Disable command works.

So we need to how to delete all configuration. It seems that uninstall plug-in is not enough.

**Comment by alexnaicuorbnet** [comment]
To delete left over plugin data:
Install SQL Server Management Studio on the machine where XProtect database is located (https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)
Open SSMS and connect.
On the left window (Object Explorer) navigate to the Databases/Surveillance/Tables/MIP.Items node.
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/115068792/d97b2ac6-fd41-4d3b-89a4-6dcfc3899c68)
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/115068792/f0641a36-c99e-4bb5-a248-97c9f388a386)
Right click on the MIP.Items node, select Edit Top 200 Rows.
On the right window select the row that has the Name column Maximizer
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/115068792/773b1b6f-f052-484c-adaf-dd9b826cd13c)
Right click and Delete, Save from the toolbar.

**Comment by alexnaicuorbnet** [comment]
It is also highly recommended to do a backup of the Milestone database through the Management Client application before making changes to the SQL server.
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/115068792/3a43701d-90d6-4de5-a3ee-759e5ad5ff0a)

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v0.9.5

Restore: not OK. CGI is not sent to camera according to Wireshark  packet.
Enable : OK
Disable : OK

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet  @EricBourque 
I upload video that we did restore operation.

https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/a7c8cb78-1e55-49f4-863c-2d9557265a25

When we click icon on SmartClient, error message "Configuration data operation failed. The server is not available".

I estimate SQL connectoin including authentication may have problem.
Do you need more log file on XProtect side or do you want remote access ?

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque  @alexnaicuorbnet 
Test version : v0.9.6 (both plug-in and service)
Test result: not OK


- On command Off command and restore command  all does not work in this version.
  No CGI was sent to camera from Maximizer service.

[2023.08.28.log](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/files/12450751/2023.08.28.log)

-When we click icon on SmartClient, error message "Configuration data operation failed. The server is not available".
  This is the same as v0.9.5

**Comment by EricBourque** [comment]
Please try again now that the commands are working on your system.

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 

Test version : v0.9.7
Test result: not OK (situation is the same as v0.9.6)

On command Off command and restore command all does not work in this version.
No CGI was sent to camera from Maximizer service.

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v0.9.8.1
