### ISSUE TITLE
[Maximizer Service]Unable to save settings and stop services

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#11]
@EricBourque  @alexnaicuorbnet 

Test version : v0.9.4 ( Maximizer Service)

**Phenomenon 1:** 
Unable to save settings even if we change on configuration menu and click OK button.

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/b3675673-1377-477a-9a55-670052577ce9)

**Phenomenon 2** 
When we select stop, service is still running.

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/a2252006-4881-477a-bc17-c07fe1d8b9b6)

**Comment by EricBourque** [comment]
Please try modifying from this path to see if it works:
"C:\ProgramData\iPRO\Maximizer Service\MaximizerServiceConfiguration.xml"

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque  @alexnaicuorbnet 
The file in our test environment is as follows and do not understand how to add parameter.

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/ab649d5d-30b9-4748-a045-8dd6f600a3f9)

We want the example on your side or want to wait next release.

**Comment by alexnaicuorbnet** [comment]
Solved this for v0.9.5 by asking for Run as administrator on the tray app.

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Configuration works well in v0.9.5.
Could you share screen capture of service setting and Management client to check this feature on your environment ?
We are not sure correct "Listening TCP port", "Management server Port" and how to configure Rules on Management client .

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Thank to clarify.
Is the configuration on Management client like Alarm definitions no need ?

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet @EricBourque 

We studied more using the same configuration as your side but not solved yet.

**Service configuration on GUI**
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/76d06326-3eb6-4c58-8ffd-72c4590c6703)

**Configuration file ( I just added ".txt" to filename for uploading here)**

[MaximizerServiceConfiguration.xml.txt](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/files/12403919/MaximizerServiceConfiguration.xml.txt)

The configured port number is not open on the PC according to netstat command.
We already did restart service, firewall configuration.


As a result, the port number 8085 is not opened on the PC according to "netstat -oan" command.
Of course, we did start process and firewall configuration.

**Log file**
There is only 1 file and ti seems there is no error.
[2023.08.21.log](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/files/12403933/2023.08.21.log)

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque  @alexnaicuorbnet 
Test version v0.9.6 (plug-in and service)

Test result : not OK

Configuration file is not updated.
Port number 8085 is not opened on the PC according to "netstat -oan" command.

[2023.08.28.log](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/files/12451086/2023.08.28.log)
![Maximizer service_log](https://github.com/ORBNETS
[MaximizerServiceConfiguration.xml.txt](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/files/12451088/MaximizerServiceConfiguration.xml.txt)
YS/i-PRO-Maximizer-Public/assets/102282918/7e048d5a-7978-4758-abea-cb0e4c3af905)

**Comment by EricBourque** [comment]
Seems OK v0.9.7

Please make sure the Maximizer Tray icon is started as Admin
Please let us know if it does not start as Admin automatically.

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/65533203/f89de3c8-3521-4205-9f51-01ae44c13956)

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
Test version ; v0.9.7

When we start manually as Administrator, configuration file was updated correctly.

How is the procedure so that we can confirm following point  ? (Restart PC, for exmaple ? )
> Please let us know if it does not start as Admin automatically.

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
We tested more in following test procedure.

1. When we logoff from Windows OS and log-in again, "Maximizer.ServiceTray" is not started automatically.
2. Then ,when we start "Maximizer.ServiceTray" manually as administrator, of course we could update configuration file correctly.

Is this expected work ?

**Comment by EricBourque** [comment]
We cannot reproduce. On our machine, the servicetray is started automatically.
Do you see this on your machine?

Execute Run and open: "shell:common startup"
You should see a Maximizer Service Manager in the starup folder
The startup folder should point to "C:\Program Files\i-PRO\i-PRO Maximizer Service\Service Tray\"

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/65533203/8dd28a4c-cf97-4825-be9d-f0f41e6d156a)

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
I checked the startup folder is the same as you.
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/6d124a7c-48fc-4eb9-bcf1-4d76c05b70b5)

But not started automatically.

Does following windows start up configuration have relation ?
"スタートアップ" means start up.

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/6f9fa725-b081-47ab-906a-8db377ed2fbc)

When we enable "_9FF30B46E12D8E8D17A334", dialog message for administrator access is shown and started automatically when login.

**Comment by EricBourque** [comment]
Yes, that is correct.
I beleive when doing a fresh installation it should be enabled by default.
Unless there are some Windows policies that can prevent it for doing that.
Thank you for finding this.

Is it OK to close the case? We will add this step in the manual.
