### ISSUE TITLE
"http://127.0.01:8085" is configured to camera's http notification configuration

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#12]
@EricBourque  @alexnaicuorbnet 
Test version: v0.9.6 (plugin and service)

**Phenomenon**
When we click button "Update alarm sending on all cameras" on management client, "http://127.0.01:8085"  is set for camera.

![http_browser](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/b963de9d-4d6c-4da8-96cb-4457f7137e2b)

**Expected work**
IPv4 address of the PC that Maximizer service is installed will be set for camera.

![Maximizer service_log](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/37e2364d-caf9-42ac-9f0a-c9dc83dcd367)

[2023.08.28.log](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/files/12451121/2023.08.28.log)

**Comment by EricBourque** [comment]
We will provide a new version soon that fixes this, please wait for v0.9.8

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v0.9.8.1

**Comment by Yoshitaka-Fukushima** [comment]
When we changed port number from 8085 to other value, and run "Update alarm sending on all cameras",
port number 8085 still used for CGI.

@EricBourque  @alexnaicuorbnet 
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/224d88a2-69f8-4488-948b-28e67253926b)

Should this behavior be limitation ? If it is technically difficult, we would like this behavior as limitation.

**Comment by EricBourque** [comment]
Sorry I am not sure what you mean. It should update the camera with the URL if you change the IP and Port.
How can we reproduce?

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
Sorry for lack of information.
When I change "Listening TCP Port" from 8085 (default) to 8095, for example and click "Update alarm sending on all cameras",
CGI uses not 8095 but uses 8085.
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/56c10263-2302-47eb-b618-2651ecf10463)

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/d0c94da2-2582-4a70-b84b-8e2b1519168e)

Should we adjust the URL on Maximizer plug-in in this case ? (Is it difficult for plug-in to change port number automatically ?)

**Comment by EricBourque** [comment]
We found that if the Management Client is not restarted, the button will not work.
We are adding code in 0.9.82 for the service to send a message when it starts so the Management Client can detect the port change.

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
Actually, we restarted Management Client after changing port number.

Could you share when plug-in reads configuration and which data from  ? 
(Does plug-in read data from "MaxmizerServiceConifguraion.xml" when Management client is started ?)

In our another test environment, we encounter another similar issue now.

**Comment by alexnaicuorbnet** [comment]
Hi Yohan,
At the moment the Management Client reads the configuration from MaximizerServiceConfiguration.xml only right after the i-PRO Extended Actions node is selected and if the Maximizer Service is running.
After that no more read is performed, unless you click away to another node and reselect i-PRO Extended Actions.
This will change, the configuration from MaximizerServiceConfiguration.xml  will be sent to the Management Client every time the Maximizer Service starts (you can edit the configuration only with the service stopped).



Alexandru Naicu
Developer
e:
***@***.*** | w:
orbnetsys.com
a: 17 Havelock Rd ,  Hastings , TN34 1BP  (UK)

​This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of ORBNET Systems. If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone. Please contact the sender if you believe you have received this email in error.
​
________________________________

**Comment by EricBourque** [comment]
I believe it was just the hhttp causing the issue.
the link after HHttpUrl was not encoded in any version until now.
We are fixing this now

**Comment by EricBourque** [comment]
Fixed in v0.9.83

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/65533203/c06e1172-bf3f-4980-bee9-335b7a532cf5)

**Comment by EricBourque** [comment]
OK, it is fixed but you will have to make a manual modification on Management Client if a previous version was installed.
This will not be necessary for new installations.

Please change the “%3d%25” to “=%” in the Management Client and save the configuration:

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/65533203/1c26fae7-92ff-498c-97cd-850061158ed7)

We now apply URL Encoding to everything after “MHttpUrl=” at runtime.

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v0.9.83

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque  @alexnaicuorbnet 
We tested in new PC , XProtect 2023R2, Windows server 2019 OS on hyper-V.

Maximizer service and Maximizer service manger are started automatically after plug-in and service installation.

Then when we start Management client, select "i-PRO Extended Action" and click "Update alarm config...", following dialog message is shown.
  
 
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/cda58390-01fe-409d-a1e5-98b1ee8d3fda)

It seems that plug-in cannot read IP address information and 127.0.0.1 was used for IP address.
Does plug-in read IP address from XML file or others ?

**Comment by EricBourque** [comment]
The IP address of the Maximizer Service is detected from inside the Maximizer service code. This is beacause the Management Client can be opened on a different machine. When the Management Client starts, it sends a broadcast message to all Maximizer services. The Maximizer Service should reply with the IP Address. So the Maximizer Service must be running for the IP to be detected. Can we have a look over a Team Viewer connection? If no, maybe it is enough with the service logs (C:\ProgramData\i-PRO\Maximizer Service\Logs\today) and Management Client logs (C:\ProgramData\Milestone\XProtect Management Client\Logs\MIPtrace.log).

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
I upload two log files.

[9.5.2023.log](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/files/12522396/9.5.2023
[MIPtrace.log](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/files/12522397/MIPtrace.log)
.log)

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v0.9.84
