### ISSUE TITLE
 'State Name', 'Tag' and 'Type' in Alarm Manager are not correct

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#13]
@EricBourque  @alexnaicuorbnet 

Test version: v0.9.7

Currently, 
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/d6819c21-a1f1-4518-9eaf-a97db825002e)

- "In progress" should be New".
- "Tag" and "Type" should be as follows

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/0facafdf-6560-41b3-b0f3-e02706dc88c3)

**Comment by EricBourque** [comment]
Fixed in 0.9.81

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in 0.9.81
