### ISSUE TITLE
Missing features as of plug-in v0.9.6 and service v0.9.7

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#15]
Test version: plug-in v0.9.6 and service v0.9.7

Sorry if you already have implemented but we cannot find following feature.

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/5807c25d-c6a7-494b-869d-d93e115f745b)

1.Feature to select each alarm as Rules and  Alarm definitions (red recatngle)

2.Feature to configure custom value (blue rectangle)

If not implemented yet and this require much time, we want to discuss at first.

**Comment by EricBourque** [comment]
Fixed in 0.9.81
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/65533203/ac608b18-286c-428b-98d5-c9b923a09241)

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque  @alexnaicuorbnet 
Test version : v0.9.81

1.Feature to select each alarm as Rules and Alarm definitions (red rectangle)
->OK

2.Feature to configure custom value (blue rectangle)
-> not OK

When we configure alarm ID other than predefined value. Maximizer service stopped due to exception error.
Predefined values mean 22,3B,45-69.

Please see the video.

When we configure value 22 and 65 (these are predefined value), service will not stop.
But when we configure value 21 and 70 (not predefined value), service will stop,

  

https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/bf362d69-cc7c-4612-8b76-e62ed9f28c1a

**Comment by EricBourque** [comment]
Ok, thank you.
I will fix all remaining today.

Kind Regards<fax:Kind%20Regards>
***@***.***<https://orbnetsys.com/>
***@***.***
Eric Bourque​​​​
Director, Chief Software Architect
t:
+41795155526<tel:+41795155526>
 |
m:
+447904345116<tel:+447904345116>
e:
***@***.******@***.***>
 |
w:
orbnetsys.com<https://orbnetsys.com/>
a:
17 Havelock Rd ,  Hastings , TN34 1BP  (UK)
***@***.***<https://www.linkedin.com/company/orbnet-systems>
***@***.***<https://www.youtube.com/channel/UCyaM_CrF8TN8bW0BkQ-V4FA>
***@***.***<https://twitter.com/orbnet_systems>
***@***.******@***.***,0.5785027,15z/data=!4m2!3m1!1s0x0:0x5e042c00a9866584?sa=X&ved=2ahUKEwiIzNrngPzzAhVE-6QKHfL9B14Q_BJ6BAhJEAU>
***@***.***<https://orbnetsys.com/>
***@***.***
***@***.***


​This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of ORBNET Systems. If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone. Please contact the sender if you believe you have received this email in error.
​

**Comment by EricBourque** [comment]
Fixed in 0.9.82

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in 0.9.82
