### ISSUE TITLE
Change the default "Display Name" from "Restore" to "Rescore to original settings"

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#17]
Test version : v0.9.84

Could you change default "Display Name" from "Restore" to "**Rescore to original settings**"  for both image scene file and privacy guard ?

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/53fa8843-2a34-4202-a2a2-29d41601fbd9)

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/20f0a2b6-225d-45f1-960d-388823e9cb0c)

**Comment by alexnaicuorbnet** [comment]
Fixed for 0.9.85-1.0.0

**Comment by alexnaicuorbnet** [comment]
What I don't like that much about "Restore to original" is that the menu item becomes a bit too large compared to the rest of its kind.

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Fixed in v0.9.85.

Thank you for your comment, It makes sense but the word "Restore" is not clear for user.
