### ISSUE TITLE
About menu "MIP Plug-ins- Maximizer" on Management Client

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#18]
Test version :v0.9.84

There is menu "MIP Plug-ins- Maximizer" but this pages seems to have no meaning.

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/78a672f6-4925-42ac-962a-18cff5285050)

Is it possible to remove or move to "i-PRO Plugins - i-PRO Maximizer" like the location of i-PRO Active Guard ?

@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Fixed by removing for 0.9.85-1.0.0

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v0.9.85
