### ISSUE TITLE
Focus control for fixed camera cannot be used for fisheye camera

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#19]
@EricBourque @alexnaicuorbnet 
Test version : v1.0.0

When we use fisheye camera,

currently, focus control for fixed camera is not active and focus control for PTZ camera is active.
  
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/b9215396-d4f3-45cc-b4ca-456572786053)

Expected
active for fixed camera and not active for PTZ camera.

Get capability response of this camera
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/1998045b-b53b-4db7-bd7f-f058175fcd66)

video_server.cam_ctrl.ptz.abf.supported=yes
video_server.cam_ctrl.focus.supported=no

means that this camera support focus control for fixed camera.

**Comment by alexnaicuorbnet** [comment]
Hi,
Until now I was looking for video_server.cam_ctrl.ptz.supported=yes, meaning that the camera is PTZ and PTZ commands should be enabled. I see that the camera in the sceenshot also has video_server.cam_ctrl.ptz.supported=yes.

Should I replace this string with something else?

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
So, is the following process not implemented?

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/6bb77e04-ff9c-48c2-8b77-c7564397b3e1)

In that case. let me discuss internally.
Your implementation and our testing require more time.

**Comment by alexnaicuorbnet** [comment]
Indeed, it seems that I overlooked these checks and they are not implemented at the moment.
What's implemented is:
PTZ Focus control and Auto Pan/Tracking commands are active when "video_server.cam_ctrl.ptz.supported=yes" is found (camera is marked as ptz).
Fixed Focus control commands are active when "video_server.cam_ctrl.ptz.supported=yes" is not found.(camera is marked as fixed).

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Thanks to clarify. This should be future version.
We want to add note to the manual this point after you make draft.
