### ISSUE TITLE
Some i-PRO camera is not shown on camera tree on i-PRO Extended actioanagement client

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#22]
Tested version ; v1.0.0 (from our internal testing)

**Procedure**
When following i-PRO cameras are registered to XProtect, camera tree on i-PRO Extended Action shows only WV-S1136.

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/e19489bd-ba1d-4007-a919-22e4eff1d3fc)

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/b71eb432-dfd9-4b9e-aaf2-99c6a9150698)

We assume this is from the difference of camera drive information but it is not clear.

**WV-S1136 and other models that works correctly,**
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/a66437c3-b9a5-4d7c-8f99-bb8d81070682)

**WV-SUD638 (not shown)**

Drive name is i-PRO/Panasonic**PTZ**

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/79d3c958-4c87-40f5-86f9-5459d7f281df)

**WV-S1111 (not shown)**

Driver information is same as WV-S1136. So the cause is not clear for us.

@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
In v1.0.0 the mac prefix "D42DC5" is used to identify i-PRO cameras (like WV-S1136).
It seems that other prefixes should be added to use as well, like ""008045".

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
We checked and found that more various MAC address is used for our existing system because we have changed company name several times in the past.

Could you add following MAC to be shown ? These are all used in our camera.


"**0080**45","**0800**23","**0080**F0","BCC342" and "4C364E"

**Comment by alexnaicuorbnet** [comment]
@Yoshitaka-Fukushima 
Ok

**Comment by alexnaicuorbnet** [comment]
Hi all,

I've added the check for other camera mac prefixes to this version

[https://res-h3.public.cdn.office.net/assets/mail/file-icon/png/exe_16x16.png]i-PRO Maximizer Plugins Setup v1.0.1.msi<https://orbnetsyscom.sharepoint.com/:u:/s/ORBNETPublic/ESMXleyJrNlNtRy0yzNoIooBaL8-MJXt9ttPSpkRBM8YLw?e=1aNmKE>
[https://res-h3.public.cdn.office.net/assets/mail/file-icon/png/exe_16x16.png]i-PRO Maximizer Service Setup v1.0.1.msi<https://orbnetsyscom.sharepoint.com/:u:/s/ORBNETPublic/EQEcu5NrPcNBlzwzASnkuU8B7FIg5ZZRrhVbAf2mCErmfw?e=h6K0ZQ>

Alexandru Naicu
Developer
e:
***@***.*** | w:
orbnetsys.com
a: 17 Havelock Rd ,  Hastings , TN34 1BP  (UK)

​This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of ORBNET Systems. If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone. Please contact the sender if you believe you have received this email in error.
​
________________________________

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Thank you for quick update.
We are testing now and only "080023" cameras are not shown.
Could you check the implementation though we continue to check ?

**Comment by Yoshitaka-Fukushima** [comment]
Sorry, our update procedure was incorrect and it is OK now.
I will report again when we complete test.

**Comment by Yoshitaka-Fukushima** [comment]
OK in v1.0.1
