### ISSUE TITLE
When changing Scene file on Smart Client, exception error occurs

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#3]
Test version : v0.9.1 released on 5th June.

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/9bca5733-1b84-4d81-8568-22e725c6b146)

************** Outer Exception **************
例外タイプ：System.InvalidCastException
例外メッセージ：型 'System.Windows.Controls.Separator' のオブジェクトを型 'System.Windows.Controls.MenuItem' にキャストできません。
例外ソース：System.Core
例外対象サイト： MoveNext
   場所 System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   場所 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   場所 Maximizer.Client.MaximizerToolbarPluginWpfUserControl.b.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
   場所 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

************** System Info **************
日時：	2023/06/15 16:30:34
マシン名：	DESKTOP-S6JNAMR
プロセッサの数：	16
OS バージョン：	Microsoft Windows NT 6.2.9200.0
64 ビット OS:	True
64 ビット プロセス：	True
IPアドレス：	fe80::98e8:9134:c283:96b2%10 (DESKTOP-S6JNAMR)
現行ユーザー：	DESKTOP-S6JNAMR\IPRO_VMS_TEST

**Comment by alexnaicuorbnet** [comment]
Solved for v0.9.3

**Comment by Yoshitaka-Fukushima** [comment]
Not fixed in v0.9.3
What kind of data do you need or do you need remote connection ?
@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Solved for v0.9.4

**Comment by Yoshitaka-Fukushima** [comment]
Test version : v0.9.4

"Restore" operation fails and the error is shown like this.
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/71370312-f707-4e0b-b785-0dac1813d032)

It is no problem for changing scene file 1,2,3 and 4.

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque  @alexnaicuorbnet 
Test version : v0.9.6 (both plug-in and service)
Test result: not OK

-Change command to Scenefile 1 to 4 and restore command all does not work in this version.
No CGI was sent to camera from Maximizer service.

[2023.08.28.log](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/files/12450774/2023.08.28.log)


-When we click icon on SmartClient, error message "Configuration data operation failed. The server is not available".
This is the same as v0.9.5

**Comment by EricBourque** [comment]
Please try again now that commands are working on your system.

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
Test version : v0.9.7
Test result: 
 -Change command to Scene file 1 to 4 and restore command all works well.

 -Error message "Configuration data operation failed. The server is not available" is still shown when we click icon on SmartClient. Is this restriction ?

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in V0.9.81
