### ISSUE TITLE
Underscore in Rule name sometimes is not shown on Smart Client

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#5]
Test version : v0.9.1 released on 5th June.

Example 1

configuration
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/c5ca492a-2aec-4244-983e-f5bcc606b506)
Smart client
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/36d884d0-aa62-40b3-ac1b-8ac050751e21)

Example2
configuration
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/83b105cd-4ca2-497e-81c4-a6dc6fa32b06)

Smart client
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/d37f9fb8-f224-4b1d-bb9c-677948ce438a)

**Comment by alexnaicuorbnet** [comment]
Solved in v0.9.2

**Comment by Yoshitaka-Fukushima** [comment]
fixed in v0.9.2 released on 26th June.
