### ISSUE TITLE
Stop Auto Pan/Tracking does not work due to incorrect URL

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#6]
Test version: 0.9.2 released on 26th June.

When running select "Stop Auto Pan/Tracking",
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/d2bbf856-ba9c-4886-98a4-8ceec59e8c55)

Currently
/cgi-bin/camctrl?atmode=off%E2%80%8B  is sent to camera and result 403 error.

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/622eec2c-7511-451c-99e4-b316e6bfd964)

Expected
/cgi-bin/camctrl?atmode=off is sent to camera

@e @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Solved for v0.9.4

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v0.9.5.
