### ISSUE TITLE
"Display name" becomes blank when close window and open again

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#7]
Test version: 0.9.2 released on 26th June.

Procedure

１．Click "Configure camera commands"

-> "Display name" is shown correctly (OK)
![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/4c2845ed-a170-47f9-b3da-e4ddcf61dcb5)

２．Close window by clicking "Cancel" or "×"button.

３．Click "Configure camera commands" again
-> "Display name" becomes blank  (**not OK**)

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/35d345ab-d432-4799-bb2e-5eecf8b8dfd1)
 
@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Fixed on 18.07 for version 0.9.3.

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in Version 0.9.3.
