### ISSUE TITLE
Focus command does not work because "HTTP POST" method is set as default instead of "HTTP GET".

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#8]
Test version: 0.9.2 released on 26th June.

Currently, POST method is set as default for following commands.

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/d1d7bb6a-cfb4-4ada-945a-f91950644490)

GET method is correct for these commands.
Could you change to "GET" method ?

@EricBourque  @alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Fixed on 18.07 for version 0.9.3.

**Comment by Yoshitaka-Fukushima** [comment]
Fixed in v0.9.3
