### ISSUE TITLE
CGI is not encrypted even if camera is registered as HTTPS

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Maximizer-Public#9]
@EricBourque  @alexnaicuorbnet 
Test version: v0.9.3

When "Yes" is set for "HTTPS enabled", CGI from Maximizer to camera is not encrypted.

![image](https://github.com/ORBNETSYS/i-PRO-Maximizer-Public/assets/102282918/07bb855a-a945-4377-9bbb-5de2dad8f60d)

Based on previous discussion, encryption should depdend on this configuration.

**Comment by alexnaicuorbnet** [comment]
Solved 25.07.23 for v0.9.4

**Comment by Yoshitaka-Fukushima** [comment]
fixed in v0.9.4
